# Generated by Django 5.2.9 on 2026-01-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("santa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="santa.event",
                    ),
                ),
                (
                    "excluded",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_by",
                        to="santa.participant",
                    ),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions_as_giver",
                        to="santa.participant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "giver", "excluded"), name="unique_exclusion"
                    )
                ],
            },
        ),
    ]
