# Generated by Django 5.2.9 on 2026-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("santa", "0002_exclusion"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("event", "giver"), name="unique_giver_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("event", "receiver"), name="unique_receiver_per_event"
            ),
        ),
    ]
